//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deploy.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Client {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Client() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Deploy.Resources.Client", typeof(Client).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Service.
        /// </summary>
        public static string AppService {
            get {
                return ResourceManager.GetString("AppService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Status Dashboard.
        /// </summary>
        public static string AzureStatusDashboard {
            get {
                return ResourceManager.GetString("AzureStatusDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculator.
        /// </summary>
        public static string Calculator {
            get {
                return ResourceManager.GetString("Calculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Careers.
        /// </summary>
        public static string Careers {
            get {
                return ResourceManager.GetString("Careers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Studies.
        /// </summary>
        public static string CaseStudies {
            get {
                return ResourceManager.GetString("CaseStudies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community.
        /// </summary>
        public static string Community {
            get {
                return ResourceManager.GetString("Community", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compliance.
        /// </summary>
        public static string Compliance {
            get {
                return ResourceManager.GetString("Compliance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datacenters.
        /// </summary>
        public static string Datacenters {
            get {
                return ResourceManager.GetString("Datacenters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string Documentation {
            get {
                return ResourceManager.GetString("Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads.
        /// </summary>
        public static string Downloads {
            get {
                return ResourceManager.GetString("Downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        public static string Facebook {
            get {
                return ResourceManager.GetString("Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        public static string Features {
            get {
                return ResourceManager.GetString("Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find a local number.
        /// </summary>
        public static string Findalocalnumber {
            get {
                return ResourceManager.GetString("Findalocalnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find a local number or submit query form.
        /// </summary>
        public static string Findalocalnumbersubmitquery {
            get {
                return ResourceManager.GetString("Findalocalnumbersubmitquery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forums.
        /// </summary>
        public static string Forums {
            get {
                return ResourceManager.GetString("Forums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Account.
        /// </summary>
        public static string FreeAccount {
            get {
                return ResourceManager.GetString("FreeAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Social.
        /// </summary>
        public static string GoSocial {
            get {
                return ResourceManager.GetString("GoSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello from Seattle..
        /// </summary>
        public static string HellofromSeattle {
            get {
                return ResourceManager.GetString("HellofromSeattle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploying your {0} App Service.
        /// </summary>
        public static string Information_DeployingHeader {
            get {
                return ResourceManager.GetString("Information_DeployingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment Completed.
        /// </summary>
        public static string Information_DeploymentCompleted {
            get {
                return ResourceManager.GetString("Information_DeploymentCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment Failed.
        /// </summary>
        public static string Information_DeploymentFailed {
            get {
                return ResourceManager.GetString("Information_DeploymentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirecting you to portal. If the portal does not open .
        /// </summary>
        public static string Information_Redirecting {
            get {
                return ResourceManager.GetString("Information_Redirecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click here.
        /// </summary>
        public static string Information_RedirectingClickhere {
            get {
                return ResourceManager.GetString("Information_RedirectingClickhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just a few more seconds. We&apos;ll be connecting to your portal experience shortly.
        /// </summary>
        public static string Information_RedirectingShortly {
            get {
                return ResourceManager.GetString("Information_RedirectingShortly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like its taking too long. To go to portal anyway .
        /// </summary>
        public static string Information_RedirectTakingTooLong {
            get {
                return ResourceManager.GetString("Information_RedirectTakingTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Portal.
        /// </summary>
        public static string ManagementPortal {
            get {
                return ResourceManager.GetString("ManagementPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketplace.
        /// </summary>
        public static string Marketplace {
            get {
                return ResourceManager.GetString("Marketplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Offers.
        /// </summary>
        public static string MemberOffers {
            get {
                return ResourceManager.GetString("MemberOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.
        /// </summary>
        public static string Microsoft {
            get {
                return ResourceManager.GetString("Microsoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Azure.
        /// </summary>
        public static string MicrosoftAzure {
            get {
                return ResourceManager.GetString("MicrosoftAzure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Azure portal.
        /// </summary>
        public static string MicrosoftAzureportal {
            get {
                return ResourceManager.GetString("MicrosoftAzureportal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Azure in China.
        /// </summary>
        public static string Mooncake {
            get {
                return ResourceManager.GetString("Mooncake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account.
        /// </summary>
        public static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newsletter.
        /// </summary>
        public static string Newsletter {
            get {
                return ResourceManager.GetString("Newsletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partners.
        /// </summary>
        public static string Partners {
            get {
                return ResourceManager.GetString("Partners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portal.
        /// </summary>
        public static string Portal {
            get {
                return ResourceManager.GetString("Portal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview Features.
        /// </summary>
        public static string PreviewFeatures {
            get {
                return ResourceManager.GetString("PreviewFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing.
        /// </summary>
        public static string Pricing {
            get {
                return ResourceManager.GetString("Pricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy &amp; Cookies.
        /// </summary>
        public static string PrivacyCookies {
            get {
                return ResourceManager.GetString("PrivacyCookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions about Azure? Contact our sales team..
        /// </summary>
        public static string QuestionsSales {
            get {
                return ResourceManager.GetString("QuestionsSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regions.
        /// </summary>
        public static string Regions {
            get {
                return ResourceManager.GetString("Regions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        public static string Resources {
            get {
                return ResourceManager.GetString("Resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rss.
        /// </summary>
        public static string Rss {
            get {
                return ResourceManager.GetString("Rss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        public static string Sales {
            get {
                return ResourceManager.GetString("Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samples.
        /// </summary>
        public static string Samples {
            get {
                return ResourceManager.GetString("Samples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string Security {
            get {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Dashboard.
        /// </summary>
        public static string ServiceDashboard {
            get {
                return ResourceManager.GetString("ServiceDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Updates.
        /// </summary>
        public static string ServiceUpdates {
            get {
                return ResourceManager.GetString("ServiceUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solutions.
        /// </summary>
        public static string Solutions {
            get {
                return ResourceManager.GetString("Solutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription.
        /// </summary>
        public static string Subscription {
            get {
                return ResourceManager.GetString("Subscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriptions.
        /// </summary>
        public static string Subscriptions {
            get {
                return ResourceManager.GetString("Subscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try Azure App Service.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trademarks.
        /// </summary>
        public static string Trademarks {
            get {
                return ResourceManager.GetString("Trademarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trust Center.
        /// </summary>
        public static string TrustCenter {
            get {
                return ResourceManager.GetString("TrustCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter.
        /// </summary>
        public static string Twitter {
            get {
                return ResourceManager.GetString("Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United States.
        /// </summary>
        public static string UnitedStates {
            get {
                return ResourceManager.GetString("UnitedStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why Azure.
        /// </summary>
        public static string WhyAzure {
            get {
                return ResourceManager.GetString("WhyAzure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YouTube.
        /// </summary>
        public static string YouTube {
            get {
                return ResourceManager.GetString("YouTube", resourceCulture);
            }
        }
    }
}
